# Generated by Django 5.0.7 on 2024-07-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TipoInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=10, unique=True)),
                ("direccion", models.CharField(max_length=255)),
                ("telefono_personal", models.CharField(max_length=15)),
                ("correo_electronico", models.EmailField(max_length=254, unique=True)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("arrendador", "Arrendador"),
                            ("arrendatario", "Arrendatario"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "m2_construidos",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("m2_totales", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad_estacionamientos", models.IntegerField()),
                ("cantidad_habitaciones", models.IntegerField()),
                ("cantidad_banos", models.IntegerField()),
                ("direccion", models.CharField(max_length=255)),
                (
                    "tipo_inmueble",
                    models.CharField(
                        choices=[
                            ("casa", "Casa"),
                            ("departamento", "Departamento"),
                            ("parcela", "Parcela"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "precio_mensual_arriendo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inmuebles",
                        to="web.comuna",
                    ),
                ),
                (
                    "arrendador",
                    models.ForeignKey(
                        limit_choices_to={"tipo_usuario": "arrendador"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inmuebles",
                        to="web.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comuna",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunas",
                to="web.region",
            ),
        ),
        migrations.CreateModel(
            name="SolicitudArriendo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_solicitud",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "inmueble",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="web.inmueble",
                    ),
                ),
                (
                    "arrendatario",
                    models.ForeignKey(
                        limit_choices_to={"tipo_usuario": "arrendatario"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="web.user",
                    ),
                ),
            ],
        ),
    ]
