# Generated by Django 5.0.7 on 2024-07-29 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=10, unique=True)),
                ("direccion", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("arrendador", "Arrendador"),
                            ("arrendatario", "Arrendatario"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                limit_choices_to={"tipo_usuario": "arrendador"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inmuebles",
                to="web.userdata",
            ),
        ),
        migrations.AlterField(
            model_name="solicitudarriendo",
            name="arrendatario",
            field=models.ForeignKey(
                limit_choices_to={"tipo_usuario": "arrendatario"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes",
                to="web.userdata",
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
