# Generated by Django 5.0.7 on 2024-07-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_userdata_alter_inmueble_arrendador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inmueble",
            name="disponible",
            field=models.BooleanField(default=True),
        ),
    ]
