# Generated by Django 5.0.7 on 2024-07-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_inmueble_disponible"),
    ]

    operations = [
        migrations.AddField(
            model_name="inmueble",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="inmuebles/"),
        ),
    ]
