# Generated by Django 5.0.7 on 2024-07-29 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_userdata_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                limit_choices_to={"tipo_usuario": "arrendador"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inmuebles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
