# Generated by Django 5.0.7 on 2024-07-29 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0006_alter_inmueble_arrendador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inmueble",
            name="tipo_inmueble",
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inmuebles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="comuna",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.comuna"
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="m2_construidos",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="m2_totales",
            field=models.FloatField(),
        ),
    ]
