# Generated by Django 5.0.7 on 2024-07-30 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0008_alter_comuna_region"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitudarriendo",
            name="estado_solicitud",
        ),
        migrations.AddField(
            model_name="solicitudarriendo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                ],
                default="pendiente",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="solicitudarriendo",
            name="arrendatario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
