# Generated by Django 5.0.7 on 2024-08-01 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_remove_solicitudarriendo_estado_solicitud_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inmueble",
            name="tipo_inmueble",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.tipoinmueble",
            ),
            preserve_default=False,
        ),
    ]
